plugins {
    id 'com.android.application' version '8.13.2' apply false
    id 'com.android.library' version '8.13.2' apply false
    id 'com.chaquo.python' version '17.0.0' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

project.ext {
    gsonVersion = '2.11.0'
    glideVersion = '4.16.0'
    media3Version = '1.5.1'
    nextlibVersion = '1.9.3-0.12.0'
    okhttpVersion = '4.12.0'
}
